/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CareerLevel = bigint;
export interface CoverLetter {
  'id' : bigint,
  'owner' : UserId,
  'body' : string,
  'createdAt' : Timestamp,
  'tone' : string,
  'shareToken' : ShareToken,
  'updatedAt' : Timestamp,
  'company' : string,
  'jobTitle' : string,
}
export interface Experience {
  'title' : string,
  'endDate' : string,
  'description' : string,
  'company' : string,
  'startDate' : string,
}
export interface InterviewNote {
  'id' : bigint,
  'question' : string,
  'sessionDate' : Timestamp,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'role' : string,
  'answer' : string,
  'score' : [] | [bigint],
}
export interface QuestProgress {
  'status' : QuestStatus,
  'completedAt' : [] | [Timestamp],
  'xpReward' : bigint,
  'questId' : string,
}
export type QuestStatus = { 'notStarted' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface Resume {
  'id' : bigint,
  'owner' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'shareToken' : ShareToken,
  'email' : string,
  'summary' : string,
  'updatedAt' : Timestamp,
  'phone' : string,
  'experiences' : Array<Experience>,
  'skills' : Array<string>,
}
export type ShareToken = string;
export interface ShopItem {
  'id' : string,
  'name' : string,
  'description' : string,
  'effect' : string,
  'xpCost' : bigint,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'careerLevel' : CareerLevel,
  'totalXp' : bigint,
  'lastLocation' : string,
  'inventory' : [] | [Array<string>],
  'createdAt' : Timestamp,
  'lastUpdated' : Timestamp,
  'levelTitle' : string,
}
export interface _SERVICE {
  'createCoverLetter' : ActorMethod<
    [string, string, string, string],
    CoverLetter
  >,
  'createInterviewNote' : ActorMethod<
    [Timestamp, string, string, string, [] | [bigint]],
    InterviewNote
  >,
  'createResume' : ActorMethod<
    [string, string, string, string, Array<Experience>, Array<string>],
    Resume
  >,
  'deleteCoverLetter' : ActorMethod<[bigint], boolean>,
  'deleteInterviewNote' : ActorMethod<[bigint], boolean>,
  'deleteResume' : ActorMethod<[bigint], boolean>,
  'generateCoverLetter' : ActorMethod<
    [string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'getCoverLetter' : ActorMethod<[bigint], [] | [CoverLetter]>,
  'getCoverLetterByToken' : ActorMethod<[ShareToken], [] | [CoverLetter]>,
  'getInterviewNote' : ActorMethod<[bigint], [] | [InterviewNote]>,
  'getMyProfile' : ActorMethod<[], UserProfile>,
  'getPlayerProfile' : ActorMethod<[], UserProfile>,
  'getResume' : ActorMethod<[bigint], [] | [Resume]>,
  'getResumeByToken' : ActorMethod<[ShareToken], [] | [Resume]>,
  'interviewQuestion' : ActorMethod<
    [string, string, [] | [string], [] | [string]],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'listCoverLetters' : ActorMethod<[], Array<CoverLetter>>,
  'listInterviewNotes' : ActorMethod<[], Array<InterviewNote>>,
  'listQuests' : ActorMethod<[], Array<QuestProgress>>,
  'listResumes' : ActorMethod<[], Array<Resume>>,
  'listShopItems' : ActorMethod<[], Array<ShopItem>>,
  'purchaseItem' : ActorMethod<
    [string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'recordNpcInteraction' : ActorMethod<[string], UserProfile>,
  'savePlayerPosition' : ActorMethod<[string], undefined>,
  'tailorResume' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'updateCoverLetter' : ActorMethod<
    [bigint, string, string, string, string],
    [] | [CoverLetter]
  >,
  'updateInterviewNote' : ActorMethod<
    [bigint, Timestamp, string, string, string, [] | [bigint]],
    [] | [InterviewNote]
  >,
  'updateResume' : ActorMethod<
    [bigint, string, string, string, string, Array<Experience>, Array<string>],
    [] | [Resume]
  >,
  'updateXP' : ActorMethod<[bigint], undefined>,
  'upsertQuestProgress' : ActorMethod<
    [string, QuestStatus, bigint],
    [QuestProgress, UserProfile]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];