/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const ShareToken = IDL.Text;
export const CoverLetter = IDL.Record({
  'id' : IDL.Nat,
  'owner' : UserId,
  'body' : IDL.Text,
  'createdAt' : Timestamp,
  'tone' : IDL.Text,
  'shareToken' : ShareToken,
  'updatedAt' : Timestamp,
  'company' : IDL.Text,
  'jobTitle' : IDL.Text,
});
export const InterviewNote = IDL.Record({
  'id' : IDL.Nat,
  'question' : IDL.Text,
  'sessionDate' : Timestamp,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'role' : IDL.Text,
  'answer' : IDL.Text,
  'score' : IDL.Opt(IDL.Nat),
});
export const Experience = IDL.Record({
  'title' : IDL.Text,
  'endDate' : IDL.Text,
  'description' : IDL.Text,
  'company' : IDL.Text,
  'startDate' : IDL.Text,
});
export const Resume = IDL.Record({
  'id' : IDL.Nat,
  'owner' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'shareToken' : ShareToken,
  'email' : IDL.Text,
  'summary' : IDL.Text,
  'updatedAt' : Timestamp,
  'phone' : IDL.Text,
  'experiences' : IDL.Vec(Experience),
  'skills' : IDL.Vec(IDL.Text),
});
export const CareerLevel = IDL.Nat;
export const UserProfile = IDL.Record({
  'id' : UserId,
  'careerLevel' : CareerLevel,
  'totalXp' : IDL.Nat,
  'lastLocation' : IDL.Text,
  'inventory' : IDL.Opt(IDL.Vec(IDL.Text)),
  'createdAt' : Timestamp,
  'lastUpdated' : Timestamp,
  'levelTitle' : IDL.Text,
});
export const QuestStatus = IDL.Variant({
  'notStarted' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const QuestProgress = IDL.Record({
  'status' : QuestStatus,
  'completedAt' : IDL.Opt(Timestamp),
  'xpReward' : IDL.Nat,
  'questId' : IDL.Text,
});
export const ShopItem = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'effect' : IDL.Text,
  'xpCost' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createCoverLetter' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [CoverLetter],
      [],
    ),
  'createInterviewNote' : IDL.Func(
      [Timestamp, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
      [InterviewNote],
      [],
    ),
  'createResume' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(Experience),
        IDL.Vec(IDL.Text),
      ],
      [Resume],
      [],
    ),
  'deleteCoverLetter' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteInterviewNote' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteResume' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'generateCoverLetter' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'getCoverLetter' : IDL.Func([IDL.Nat], [IDL.Opt(CoverLetter)], []),
  'getCoverLetterByToken' : IDL.Func(
      [ShareToken],
      [IDL.Opt(CoverLetter)],
      ['query'],
    ),
  'getInterviewNote' : IDL.Func([IDL.Nat], [IDL.Opt(InterviewNote)], []),
  'getMyProfile' : IDL.Func([], [UserProfile], []),
  'getPlayerProfile' : IDL.Func([], [UserProfile], []),
  'getResume' : IDL.Func([IDL.Nat], [IDL.Opt(Resume)], []),
  'getResumeByToken' : IDL.Func([ShareToken], [IDL.Opt(Resume)], ['query']),
  'interviewQuestion' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'listCoverLetters' : IDL.Func([], [IDL.Vec(CoverLetter)], []),
  'listInterviewNotes' : IDL.Func([], [IDL.Vec(InterviewNote)], []),
  'listQuests' : IDL.Func([], [IDL.Vec(QuestProgress)], []),
  'listResumes' : IDL.Func([], [IDL.Vec(Resume)], []),
  'listShopItems' : IDL.Func([], [IDL.Vec(ShopItem)], ['query']),
  'purchaseItem' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'recordNpcInteraction' : IDL.Func([IDL.Text], [UserProfile], []),
  'savePlayerPosition' : IDL.Func([IDL.Text], [], []),
  'tailorResume' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'updateCoverLetter' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Opt(CoverLetter)],
      [],
    ),
  'updateInterviewNote' : IDL.Func(
      [IDL.Nat, Timestamp, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
      [IDL.Opt(InterviewNote)],
      [],
    ),
  'updateResume' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(Experience),
        IDL.Vec(IDL.Text),
      ],
      [IDL.Opt(Resume)],
      [],
    ),
  'updateXP' : IDL.Func([IDL.Nat], [], []),
  'upsertQuestProgress' : IDL.Func(
      [IDL.Text, QuestStatus, IDL.Nat],
      [QuestProgress, UserProfile],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const ShareToken = IDL.Text;
  const CoverLetter = IDL.Record({
    'id' : IDL.Nat,
    'owner' : UserId,
    'body' : IDL.Text,
    'createdAt' : Timestamp,
    'tone' : IDL.Text,
    'shareToken' : ShareToken,
    'updatedAt' : Timestamp,
    'company' : IDL.Text,
    'jobTitle' : IDL.Text,
  });
  const InterviewNote = IDL.Record({
    'id' : IDL.Nat,
    'question' : IDL.Text,
    'sessionDate' : Timestamp,
    'owner' : UserId,
    'createdAt' : Timestamp,
    'role' : IDL.Text,
    'answer' : IDL.Text,
    'score' : IDL.Opt(IDL.Nat),
  });
  const Experience = IDL.Record({
    'title' : IDL.Text,
    'endDate' : IDL.Text,
    'description' : IDL.Text,
    'company' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const Resume = IDL.Record({
    'id' : IDL.Nat,
    'owner' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'shareToken' : ShareToken,
    'email' : IDL.Text,
    'summary' : IDL.Text,
    'updatedAt' : Timestamp,
    'phone' : IDL.Text,
    'experiences' : IDL.Vec(Experience),
    'skills' : IDL.Vec(IDL.Text),
  });
  const CareerLevel = IDL.Nat;
  const UserProfile = IDL.Record({
    'id' : UserId,
    'careerLevel' : CareerLevel,
    'totalXp' : IDL.Nat,
    'lastLocation' : IDL.Text,
    'inventory' : IDL.Opt(IDL.Vec(IDL.Text)),
    'createdAt' : Timestamp,
    'lastUpdated' : Timestamp,
    'levelTitle' : IDL.Text,
  });
  const QuestStatus = IDL.Variant({
    'notStarted' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const QuestProgress = IDL.Record({
    'status' : QuestStatus,
    'completedAt' : IDL.Opt(Timestamp),
    'xpReward' : IDL.Nat,
    'questId' : IDL.Text,
  });
  const ShopItem = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'effect' : IDL.Text,
    'xpCost' : IDL.Nat,
  });

  return IDL.Service({
    'createCoverLetter' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [CoverLetter],
        [],
      ),
    'createInterviewNote' : IDL.Func(
        [Timestamp, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
        [InterviewNote],
        [],
      ),
    'createResume' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(Experience),
          IDL.Vec(IDL.Text),
        ],
        [Resume],
        [],
      ),
    'deleteCoverLetter' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteInterviewNote' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteResume' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'generateCoverLetter' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'getCoverLetter' : IDL.Func([IDL.Nat], [IDL.Opt(CoverLetter)], []),
    'getCoverLetterByToken' : IDL.Func(
        [ShareToken],
        [IDL.Opt(CoverLetter)],
        ['query'],
      ),
    'getInterviewNote' : IDL.Func([IDL.Nat], [IDL.Opt(InterviewNote)], []),
    'getMyProfile' : IDL.Func([], [UserProfile], []),
    'getPlayerProfile' : IDL.Func([], [UserProfile], []),
    'getResume' : IDL.Func([IDL.Nat], [IDL.Opt(Resume)], []),
    'getResumeByToken' : IDL.Func([ShareToken], [IDL.Opt(Resume)], ['query']),
    'interviewQuestion' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'listCoverLetters' : IDL.Func([], [IDL.Vec(CoverLetter)], []),
    'listInterviewNotes' : IDL.Func([], [IDL.Vec(InterviewNote)], []),
    'listQuests' : IDL.Func([], [IDL.Vec(QuestProgress)], []),
    'listResumes' : IDL.Func([], [IDL.Vec(Resume)], []),
    'listShopItems' : IDL.Func([], [IDL.Vec(ShopItem)], ['query']),
    'purchaseItem' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'recordNpcInteraction' : IDL.Func([IDL.Text], [UserProfile], []),
    'savePlayerPosition' : IDL.Func([IDL.Text], [], []),
    'tailorResume' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'updateCoverLetter' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Opt(CoverLetter)],
        [],
      ),
    'updateInterviewNote' : IDL.Func(
        [IDL.Nat, Timestamp, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
        [IDL.Opt(InterviewNote)],
        [],
      ),
    'updateResume' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(Experience),
          IDL.Vec(IDL.Text),
        ],
        [IDL.Opt(Resume)],
        [],
      ),
    'updateXP' : IDL.Func([IDL.Nat], [], []),
    'upsertQuestProgress' : IDL.Func(
        [IDL.Text, QuestStatus, IDL.Nat],
        [QuestProgress, UserProfile],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };
