/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ShopItem {
    id: string;
    name: string;
    description: string;
    effect: string;
    xpCost: bigint;
}
export type UserId = Principal;
export type Timestamp = bigint;
export interface QuestProgress {
    status: QuestStatus;
    completedAt?: Timestamp;
    xpReward: bigint;
    questId: string;
}
export interface Experience {
    title: string;
    endDate: string;
    description: string;
    company: string;
    startDate: string;
}
export interface CoverLetter {
    id: bigint;
    owner: UserId;
    body: string;
    createdAt: Timestamp;
    tone: string;
    shareToken: ShareToken;
    updatedAt: Timestamp;
    company: string;
    jobTitle: string;
}
export interface Resume {
    id: bigint;
    owner: UserId;
    name: string;
    createdAt: Timestamp;
    shareToken: ShareToken;
    email: string;
    summary: string;
    updatedAt: Timestamp;
    phone: string;
    experiences: Array<Experience>;
    skills: Array<string>;
}
export type CareerLevel = bigint;
export interface InterviewNote {
    id: bigint;
    question: string;
    sessionDate: Timestamp;
    owner: UserId;
    createdAt: Timestamp;
    role: string;
    answer: string;
    score?: bigint;
}
export interface UserProfile {
    id: UserId;
    careerLevel: CareerLevel;
    totalXp: bigint;
    lastLocation: string;
    inventory?: Array<string>;
    createdAt: Timestamp;
    lastUpdated: Timestamp;
    levelTitle: string;
}
export type ShareToken = string;
export enum QuestStatus {
    notStarted = "notStarted",
    completed = "completed",
    inProgress = "inProgress"
}
export interface backendInterface {
    createCoverLetter(jobTitle: string, company: string, body: string, tone: string): Promise<CoverLetter>;
    createInterviewNote(sessionDate: Timestamp, role: string, question: string, answer: string, score: bigint | null): Promise<InterviewNote>;
    createResume(name: string, email: string, phone: string, summary: string, experiences: Array<Experience>, skills: Array<string>): Promise<Resume>;
    deleteCoverLetter(id: bigint): Promise<boolean>;
    deleteInterviewNote(id: bigint): Promise<boolean>;
    deleteResume(id: bigint): Promise<boolean>;
    generateCoverLetter(jobTitle: string, company: string, background: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getCoverLetter(id: bigint): Promise<CoverLetter | null>;
    getCoverLetterByToken(token: ShareToken): Promise<CoverLetter | null>;
    getInterviewNote(id: bigint): Promise<InterviewNote | null>;
    getMyProfile(): Promise<UserProfile>;
    getPlayerProfile(): Promise<UserProfile>;
    getResume(id: bigint): Promise<Resume | null>;
    getResumeByToken(token: ShareToken): Promise<Resume | null>;
    interviewQuestion(jobTitle: string, category: string, previousQuestion: string | null, userAnswer: string | null): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    listCoverLetters(): Promise<Array<CoverLetter>>;
    listInterviewNotes(): Promise<Array<InterviewNote>>;
    listQuests(): Promise<Array<QuestProgress>>;
    listResumes(): Promise<Array<Resume>>;
    listShopItems(): Promise<Array<ShopItem>>;
    purchaseItem(itemId: string): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    recordNpcInteraction(npcId: string): Promise<UserProfile>;
    savePlayerPosition(location: string): Promise<void>;
    tailorResume(jobDescription: string, resumeText: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateCoverLetter(id: bigint, jobTitle: string, company: string, body: string, tone: string): Promise<CoverLetter | null>;
    updateInterviewNote(id: bigint, sessionDate: Timestamp, role: string, question: string, answer: string, score: bigint | null): Promise<InterviewNote | null>;
    updateResume(id: bigint, name: string, email: string, phone: string, summary: string, experiences: Array<Experience>, skills: Array<string>): Promise<Resume | null>;
    updateXP(amount: bigint): Promise<void>;
    upsertQuestProgress(questId: string, status: QuestStatus, xpReward: bigint): Promise<[QuestProgress, UserProfile]>;
}
import type { CareerLevel as _CareerLevel, CoverLetter as _CoverLetter, InterviewNote as _InterviewNote, QuestProgress as _QuestProgress, QuestStatus as _QuestStatus, Resume as _Resume, Timestamp as _Timestamp, UserId as _UserId, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createCoverLetter(arg0: string, arg1: string, arg2: string, arg3: string): Promise<CoverLetter> {
        if (this.processError) {
            try {
                const result = await this.actor.createCoverLetter(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCoverLetter(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createInterviewNote(arg0: Timestamp, arg1: string, arg2: string, arg3: string, arg4: bigint | null): Promise<InterviewNote> {
        if (this.processError) {
            try {
                const result = await this.actor.createInterviewNote(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
                return from_candid_InterviewNote_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInterviewNote(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
            return from_candid_InterviewNote_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async createResume(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Array<Experience>, arg5: Array<string>): Promise<Resume> {
        if (this.processError) {
            try {
                const result = await this.actor.createResume(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createResume(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async deleteCoverLetter(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCoverLetter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCoverLetter(arg0);
            return result;
        }
    }
    async deleteInterviewNote(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInterviewNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInterviewNote(arg0);
            return result;
        }
    }
    async deleteResume(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteResume(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteResume(arg0);
            return result;
        }
    }
    async generateCoverLetter(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.generateCoverLetter(arg0, arg1, arg2);
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateCoverLetter(arg0, arg1, arg2);
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoverLetter(arg0: bigint): Promise<CoverLetter | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoverLetter(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoverLetter(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoverLetterByToken(arg0: ShareToken): Promise<CoverLetter | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoverLetterByToken(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoverLetterByToken(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInterviewNote(arg0: bigint): Promise<InterviewNote | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInterviewNote(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInterviewNote(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_UserProfile_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_UserProfile_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayerProfile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerProfile();
                return from_candid_UserProfile_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerProfile();
            return from_candid_UserProfile_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResume(arg0: bigint): Promise<Resume | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getResume(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResume(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResumeByToken(arg0: ShareToken): Promise<Resume | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getResumeByToken(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResumeByToken(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async interviewQuestion(arg0: string, arg1: string, arg2: string | null, arg3: string | null): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.interviewQuestion(arg0, arg1, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3));
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.interviewQuestion(arg0, arg1, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3));
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async listCoverLetters(): Promise<Array<CoverLetter>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCoverLetters();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCoverLetters();
            return result;
        }
    }
    async listInterviewNotes(): Promise<Array<InterviewNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInterviewNotes();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInterviewNotes();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async listQuests(): Promise<Array<QuestProgress>> {
        if (this.processError) {
            try {
                const result = await this.actor.listQuests();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listQuests();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async listResumes(): Promise<Array<Resume>> {
        if (this.processError) {
            try {
                const result = await this.actor.listResumes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listResumes();
            return result;
        }
    }
    async listShopItems(): Promise<Array<ShopItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listShopItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listShopItems();
            return result;
        }
    }
    async purchaseItem(arg0: string): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.purchaseItem(arg0);
                return from_candid_variant_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purchaseItem(arg0);
            return from_candid_variant_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordNpcInteraction(arg0: string): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.recordNpcInteraction(arg0);
                return from_candid_UserProfile_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordNpcInteraction(arg0);
            return from_candid_UserProfile_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async savePlayerPosition(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePlayerPosition(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePlayerPosition(arg0);
            return result;
        }
    }
    async tailorResume(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.tailorResume(arg0, arg1);
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.tailorResume(arg0, arg1);
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCoverLetter(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string): Promise<CoverLetter | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCoverLetter(arg0, arg1, arg2, arg3, arg4);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCoverLetter(arg0, arg1, arg2, arg3, arg4);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateInterviewNote(arg0: bigint, arg1: Timestamp, arg2: string, arg3: string, arg4: string, arg5: bigint | null): Promise<InterviewNote | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInterviewNote(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5));
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInterviewNote(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5));
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateResume(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: Array<Experience>, arg6: Array<string>): Promise<Resume | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateResume(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateResume(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateXP(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateXP(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateXP(arg0);
            return result;
        }
    }
    async upsertQuestProgress(arg0: string, arg1: QuestStatus, arg2: bigint): Promise<[QuestProgress, UserProfile]> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertQuestProgress(arg0, to_candid_QuestStatus_n21(this._uploadFile, this._downloadFile, arg1), arg2);
                return [
                    from_candid_QuestProgress_n15(this._uploadFile, this._downloadFile, result[0]),
                    from_candid_UserProfile_n8(this._uploadFile, this._downloadFile, result[1])
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertQuestProgress(arg0, to_candid_QuestStatus_n21(this._uploadFile, this._downloadFile, arg1), arg2);
            return [
                from_candid_QuestProgress_n15(this._uploadFile, this._downloadFile, result[0]),
                from_candid_UserProfile_n8(this._uploadFile, this._downloadFile, result[1])
            ];
        }
    }
}
function from_candid_InterviewNote_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InterviewNote): InterviewNote {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_QuestProgress_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestProgress): QuestProgress {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_QuestStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestStatus): QuestStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<string>]): Array<string> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Resume]): Resume | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CoverLetter]): CoverLetter | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InterviewNote]): InterviewNote | null {
    return value.length === 0 ? null : from_candid_InterviewNote_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _QuestStatus;
    completedAt: [] | [_Timestamp];
    xpReward: bigint;
    questId: string;
}): {
    status: QuestStatus;
    completedAt?: Timestamp;
    xpReward: bigint;
    questId: string;
} {
    return {
        status: from_candid_QuestStatus_n17(_uploadFile, _downloadFile, value.status),
        completedAt: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.completedAt)),
        xpReward: value.xpReward,
        questId: value.questId
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    question: string;
    sessionDate: _Timestamp;
    owner: _UserId;
    createdAt: _Timestamp;
    role: string;
    answer: string;
    score: [] | [bigint];
}): {
    id: bigint;
    question: string;
    sessionDate: Timestamp;
    owner: UserId;
    createdAt: Timestamp;
    role: string;
    answer: string;
    score?: bigint;
} {
    return {
        id: value.id,
        question: value.question,
        sessionDate: value.sessionDate,
        owner: value.owner,
        createdAt: value.createdAt,
        role: value.role,
        answer: value.answer,
        score: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.score))
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    careerLevel: _CareerLevel;
    totalXp: bigint;
    lastLocation: string;
    inventory: [] | [Array<string>];
    createdAt: _Timestamp;
    lastUpdated: _Timestamp;
    levelTitle: string;
}): {
    id: UserId;
    careerLevel: CareerLevel;
    totalXp: bigint;
    lastLocation: string;
    inventory?: Array<string>;
    createdAt: Timestamp;
    lastUpdated: Timestamp;
    levelTitle: string;
} {
    return {
        id: value.id,
        careerLevel: value.careerLevel,
        totalXp: value.totalXp,
        lastLocation: value.lastLocation,
        inventory: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.inventory)),
        createdAt: value.createdAt,
        lastUpdated: value.lastUpdated,
        levelTitle: value.levelTitle
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notStarted: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): QuestStatus {
    return "notStarted" in value ? QuestStatus.notStarted : "completed" in value ? QuestStatus.completed : "inProgress" in value ? QuestStatus.inProgress : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InterviewNote>): Array<InterviewNote> {
    return value.map((x)=>from_candid_InterviewNote_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QuestProgress>): Array<QuestProgress> {
    return value.map((x)=>from_candid_QuestProgress_n15(_uploadFile, _downloadFile, x));
}
function to_candid_QuestStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestStatus): _QuestStatus {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestStatus): {
    notStarted: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == QuestStatus.notStarted ? {
        notStarted: null
    } : value == QuestStatus.completed ? {
        completed: null
    } : value == QuestStatus.inProgress ? {
        inProgress: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
